# Makefile
# Licensed under the MIT license.

CC = clang
CFLAGS = -O3 -pedantic -std=c99 -Wall -Wextra

all: day01a day01b day02a day02b day03a day03b day04a day04b

day01a: day01a.c
	$(CC) $(CFLAGS) $< -o $@

day01b: day01b.c
	$(CC) $(CFLAGS) $< -o $@

day02a: day02a.c
	$(CC) $(CFLAGS) $< -o $@

day02b: day02b.c
	$(CC) $(CFLAGS) $< -o $@

day03a: day03a.c
	$(CC) $(CFLAGS) $< -o $@

day03b: day03b.c
	$(CC) $(CFLAGS) $< -o $@

day04a: day04a.c
	$(CC) $(CFLAGS) $< -o $@

day04b: day04b.c
	$(CC) $(CFLAGS) $< -o $@
